version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    vendor: false
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]

