kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-prometheus-1
  labels:
    type: local
spec:
  storageClassName: prom-manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv-prometheus-1"