apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: thanos-gateway
  labels:
    app: thanos-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-gateway
  serviceName: thanos-gateway
  template:
    metadata:
      labels:
        app: thanos-gateway
        thanos-store-api: "true"
    spec:
      containers:
      - name: thanos
        image: improbable/thanos:v0.3.0-rc.0
        args:
        - store
        - --log.level=debug
        - --data-dir=/data
        - --cluster.disable
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        - |
          --objstore.config=type: S3
          config:
            bucket: demo-bucket
            access_key: smth
            secret_key: Need8Chars
            endpoint: %%S3_ENDPOINT%%
            insecure: true
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-gateway
  name: thanos-gateway
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    app: thanos-gateway
  type: NodePort
