global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus_one'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 100ms
    static_configs:
      - targets: ['localhost:9001']

  - job_name: 'minio'
    scrape_interval: 100ms
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'thanos_sidecar_one'
    scrape_interval: 100ms
    static_configs:
      - targets: ['thanos_sidecar_one:10901', 'thanos_sidecar_one:10902']

  - job_name: 'thanos_querier'
    scrape_interval: 100ms
    static_configs:
      - targets: ['thanos_querier:10901', 'thanos_querier:10902']

  - job_name: 'thanos_compactor'
    scrape_interval: 100ms
    static_configs:
      - targets: ['thanos_compactor:10901', 'thanos_compactor:10902']

  - job_name: 'thanos_store'
    scrape_interval: 100ms
    static_configs:
      - targets: ['thanos_store:10901', 'thanos_store:10902']
