on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
name: busybox-update workflow
permissions:  
  contents: read

jobs:
  checkVersionAndCreatePR:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run busybox updater
        run: |
          chmod +x ./scripts/busybox-updater.sh
          ./scripts/busybox-updater.sh
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Updates busybox SHA'
          branch: update-sha-action
          delete-branch: true
          title: '*: Updates Prometheus BusyBox image SHAs'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: busybox, automated pr
